# Generated by Django 4.2 on 2023-07-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("number_of_copy", models.IntegerField()),
                (
                    "catagory",
                    models.CharField(
                        choices=[
                            ("Mystery", "Mystery"),
                            ("Thrill", "Thriller"),
                            ("Sci-fi", "Sci-fi"),
                            ("Horror", "Horror"),
                            ("Humor", "Humor"),
                        ],
                        max_length=30,
                    ),
                ),
                ("author", models.CharField(max_length=30)),
                ("first_pub", models.DateTimeField(auto_now_add=True)),
                ("last_pub", models.DateTimeField(auto_now=True)),
                ("description", models.TextField()),
            ],
        ),
    ]
