# Generated by Django 4.2 on 2023-07-26 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0003_alter_borrows_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="borrows",
            unique_together=set(),
        ),
    ]
