# Generated by Django 4.2 on 2023-07-26 18:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("first_app", "0004_alter_borrows_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="borrows",
            unique_together={("user", "book")},
        ),
    ]
