# Generated by Django 4.2 on 2023-07-29 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0005_alter_borrows_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrows",
            name="expiry",
            field=models.DateField(
                default=datetime.datetime(2023, 8, 12, 10, 46, 42, 316272)
            ),
        ),
    ]
