# Generated by Django 4.2 on 2023-07-30 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0010_reservations_is_reserved_alter_borrows_expiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrows",
            name="expiry",
            field=models.DateField(
                default=datetime.datetime(2023, 7, 30, 18, 22, 24, 97655)
            ),
        ),
    ]
