# Generated by Django 4.2 on 2023-07-30 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0011_alter_borrows_expiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrows",
            name="fine",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="borrows",
            name="expiry",
            field=models.DateField(
                default=datetime.datetime(2023, 7, 30, 21, 5, 41, 272354)
            ),
        ),
    ]
