# Generated by Django 4.2 on 2023-07-30 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0012_borrows_fine_alter_borrows_expiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrows",
            name="expiry",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 30, 21, 15, 41, 674074)
            ),
        ),
    ]
